<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE USERS
[
<!ELEMENT USERS (USERDATA+)>
<!ELEMENT USERDATA (NICKNAME,PASSWORD)>
<!ELEMENT NICKNAME (#PCDATA)>
<!ELEMENT PASSWORD (#PCDATA)>
]>
<USERS>
  <USERDATA>
    <NICKNAME>ROOT</NICKNAME>
    <PASSWORD>ROOT</PASSWORD>
</USERDATA>
  <USERDATA>
    <NICKNAME>EMILIANO</NICKNAME>
    <PASSWORD>ADMIN</PASSWORD>
</USERDATA>
  <USERDATA>
    <NICKNAME>ZABDIEL</NICKNAME>
    <PASSWORD>ADMIN</PASSWORD>
</USERDATA>
</USERS>
